tap "caskroom/cask"

cask "dropbox"
cask "1password"
cask "google-chrome"
# cask "opera"
cask "firefox"
cask "hammerspoon"
# cask "dash"
cask "atom"
cask "textmate"
cask "skype"
cask "vlc"

tap "caskroom/fonts"
cask "font-hack"